[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
freelunch = "AXnYea6Je9Ui31N6cY8y2oPfppETrh5sr6U31B5A77VQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
